import pic0png from "@/assets/gallery/0.png";
import pic1png from "@/assets/gallery/1.png";
import pic2png from "@/assets/gallery/2.png";
import pic3png from "@/assets/gallery/3.png";
import pic4png from "@/assets/gallery/4.png";
import pic5png from "@/assets/gallery/5.png";
import pic6png from "@/assets/gallery/6.png";
import pic7png from "@/assets/gallery/7.png";

import pic0jpg from "@/assets/gallery/0.jpg";
import pic1jpg from "@/assets/gallery/1.jpg";
import pic2jpg from "@/assets/gallery/2.jpg";
import pic3jpg from "@/assets/gallery/3.jpg";
import pic4jpg from "@/assets/gallery/4.jpg";
import pic5jpg from "@/assets/gallery/5.jpg";
import pic6jpg from "@/assets/gallery/6.jpg";
import pic7jpg from "@/assets/gallery/7.jpg";
import pic8jpg from "@/assets/gallery/8.jpg";
import pic9jpg from "@/assets/gallery/9.jpg";
import pic10jpg from "@/assets/gallery/10.jpg";
import pic11jpg from "@/assets/gallery/11.jpg";
import pic12jpg from "@/assets/gallery/12.jpg";
import pic13jpg from "@/assets/gallery/13.jpg";
import pic14jpg from "@/assets/gallery/14.jpg";
import pic15jpg from "@/assets/gallery/15.jpg";
import pic16jpg from "@/assets/gallery/16.jpg";
import pic17jpg from "@/assets/gallery/17.jpg";
import pic18jpg from "@/assets/gallery/18.jpg";
import pic19jpg from "@/assets/gallery/19.jpg";
import pic20jpg from "@/assets/gallery/20.jpg";
import pic21jpg from "@/assets/gallery/21.jpg";
import pic22jpg from "@/assets/gallery/22.jpg";
import pic23jpg from "@/assets/gallery/23.jpg";
import pic24jpg from "@/assets/gallery/24.jpg";
import pic25jpg from "@/assets/gallery/25.jpg";
import pic26jpg from "@/assets/gallery/26.jpg";
import pic27jpg from "@/assets/gallery/27.jpg";
import pic28jpg from "@/assets/gallery/28.jpg";
import pic29jpg from "@/assets/gallery/29.jpg";
import pic30jpg from "@/assets/gallery/30.jpg";
import pic31jpg from "@/assets/gallery/31.jpg";
import pic32jpg from "@/assets/gallery/32.jpg";
import pic33jpg from "@/assets/gallery/33.jpg";
import pic34jpg from "@/assets/gallery/34.jpg";
import pic35jpg from "@/assets/gallery/35.jpg";
import pic36jpg from "@/assets/gallery/36.jpg";
import pic37jpg from "@/assets/gallery/37.jpg";
import pic38jpg from "@/assets/gallery/38.jpg";
import pic39jpg from "@/assets/gallery/39.jpg";
import pic40jpg from "@/assets/gallery/40.jpg";
import pic41jpg from "@/assets/gallery/41.jpg";
import pic42jpg from "@/assets/gallery/42.jpg";
import pic43jpg from "@/assets/gallery/43.jpg";
import pic44jpg from "@/assets/gallery/44.jpg";
import pic45jpg from "@/assets/gallery/45.jpg";
import pic46jpg from "@/assets/gallery/46.jpg";
import pic47jpg from "@/assets/gallery/47.jpg";
import pic48jpg from "@/assets/gallery/48.jpg";
import pic49jpg from "@/assets/gallery/49.jpg";
import pic50jpg from "@/assets/gallery/50.jpg";
import pic51jpg from "@/assets/gallery/51.jpg";
import pic52jpg from "@/assets/gallery/52.jpg";
import pic53jpg from "@/assets/gallery/53.jpg";
import pic54jpg from "@/assets/gallery/54.jpg";
import pic55jpg from "@/assets/gallery/55.jpg";
import pic56jpg from "@/assets/gallery/56.jpg";
import pic57jpg from "@/assets/gallery/57.jpg";
import pic58jpg from "@/assets/gallery/58.jpg";
import pic59jpg from "@/assets/gallery/59.jpg";
import pic60jpg from "@/assets/gallery/60.jpg";
import pic61jpg from "@/assets/gallery/61.jpg";
import pic62jpg from "@/assets/gallery/62.jpg";
import pic63jpg from "@/assets/gallery/63.jpg";
import pic64jpg from "@/assets/gallery/64.jpg";
import pic65jpg from "@/assets/gallery/65.jpg";
import pic66jpg from "@/assets/gallery/66.jpg";
import pic67jpg from "@/assets/gallery/67.jpg";
import pic68jpg from "@/assets/gallery/68.jpg";
import pic69jpg from "@/assets/gallery/69.jpg";
import pic70jpg from "@/assets/gallery/70.jpg";
import pic71jpg from "@/assets/gallery/71.jpg";
import pic72jpg from "@/assets/gallery/72.jpg";
import pic73jpg from "@/assets/gallery/73.jpg";
import pic74jpg from "@/assets/gallery/74.jpg";
import pic75jpg from "@/assets/gallery/75.jpg";
import pic76jpg from "@/assets/gallery/76.jpg";
import pic77jpg from "@/assets/gallery/77.jpg";
import pic78jpg from "@/assets/gallery/78.jpg";
import pic79jpg from "@/assets/gallery/79.jpg";
import pic80jpg from "@/assets/gallery/80.jpg";

import Image from "next/image";

export default function Gallery() {

    return (
        <>
            <div className="flex p-5 sm:p-8">
                <div className="columns-1 gap-5 sm:columns-2 sm:gap-8 md:columns-3 lg:columns-4 [&>img:not(:first-child)]:mt-8">
                    <Image alt={`pic0png`} src={pic0png.src} />
                    <Image alt={`pic1png`} src={pic1png.src} />
                    <Image alt={`pic2png`} src={pic2png.src} />
                    <Image alt={`pic3png`} src={pic3png.src} />
                    <Image alt={`pic4png`} src={pic4png.src} />
                    <Image alt={`pic5png`} src={pic5png.src} />
                    <Image alt={`pic6png`} src={pic6png.src} />
                    <Image alt={`pic7png`} src={pic7png.src} />
                    <Image alt={`pic0jpg`} src={pic0jpg.src} />
                    <Image alt={`pic1jpg`} src={pic1jpg.src} />
                    <Image alt={`pic2jpg`} src={pic2jpg.src} />
                    <Image alt={`pic3jpg`} src={pic3jpg.src} />
                    <Image alt={`pic4jpg`} src={pic4jpg.src} />
                    <Image alt={`pic5jpg`} src={pic5jpg.src} />
                    <Image alt={`pic6jpg`} src={pic6jpg.src} />
                    <Image alt={`pic7jpg`} src={pic7jpg.src} />
                    <Image alt={`pic8jpg`} src={pic8jpg.src} />
                    <Image alt={`pic9jpg`} src={pic9jpg.src} />
                    <Image alt={`pic10jpg`} src={pic10jpg.src} />
                    <Image alt={`pic11jpg`} src={pic11jpg.src} />
                    <Image alt={`pic12jpg`} src={pic12jpg.src} />
                    <Image alt={`pic13jpg`} src={pic13jpg.src} />
                    <Image alt={`pic14jpg`} src={pic14jpg.src} />
                    <Image alt={`pic15jpg`} src={pic15jpg.src} />
                    <Image alt={`pic16jpg`} src={pic16jpg.src} />
                    <Image alt={`pic17jpg`} src={pic17jpg.src} />
                    <Image alt={`pic18jpg`} src={pic18jpg.src} />
                    <Image alt={`pic19jpg`} src={pic19jpg.src} />
                    <Image alt={`pic20jpg`} src={pic20jpg.src} />
                    <Image alt={`pic21jpg`} src={pic21jpg.src} />
                    <Image alt={`pic22jpg`} src={pic22jpg.src} />
                    <Image alt={`pic23jpg`} src={pic23jpg.src} />
                    <Image alt={`pic24jpg`} src={pic24jpg.src} />
                    <Image alt={`pic25jpg`} src={pic25jpg.src} />
                    <Image alt={`pic26jpg`} src={pic26jpg.src} />
                    <Image alt={`pic27jpg`} src={pic27jpg.src} />
                    <Image alt={`pic28jpg`} src={pic28jpg.src} />
                    <Image alt={`pic29jpg`} src={pic29jpg.src} />
                    <Image alt={`pic30jpg`} src={pic30jpg.src} />
                    <Image alt={`pic31jpg`} src={pic31jpg.src} />
                    <Image alt={`pic32jpg`} src={pic32jpg.src} />
                    <Image alt={`pic33jpg`} src={pic33jpg.src} />
                    <Image alt={`pic34jpg`} src={pic34jpg.src} />
                    <Image alt={`pic35jpg`} src={pic35jpg.src} />
                    <Image alt={`pic36jpg`} src={pic36jpg.src} />
                    <Image alt={`pic37jpg`} src={pic37jpg.src} />
                    <Image alt={`pic38jpg`} src={pic38jpg.src} />
                    <Image alt={`pic39jpg`} src={pic39jpg.src} />
                    <Image alt={`pic40jpg`} src={pic40jpg.src} />
                    <Image alt={`pic41jpg`} src={pic41jpg.src} />
                    <Image alt={`pic42jpg`} src={pic42jpg.src} />
                    <Image alt={`pic43jpg`} src={pic43jpg.src} />
                    <Image alt={`pic44jpg`} src={pic44jpg.src} />
                    <Image alt={`pic45jpg`} src={pic45jpg.src} />
                    <Image alt={`pic46jpg`} src={pic46jpg.src} />
                    <Image alt={`pic47jpg`} src={pic47jpg.src} />
                    <Image alt={`pic48jpg`} src={pic48jpg.src} />
                    <Image alt={`pic49jpg`} src={pic49jpg.src} />
                    <Image alt={`pic50jpg`} src={pic50jpg.src} />
                    <Image alt={`pic51jpg`} src={pic51jpg.src} />
                    <Image alt={`pic52jpg`} src={pic52jpg.src} />
                    <Image alt={`pic53jpg`} src={pic53jpg.src} />
                    <Image alt={`pic54jpg`} src={pic54jpg.src} />
                    <Image alt={`pic55jpg`} src={pic55jpg.src} />
                    <Image alt={`pic56jpg`} src={pic56jpg.src} />
                    <Image alt={`pic57jpg`} src={pic57jpg.src} />
                    <Image alt={`pic58jpg`} src={pic58jpg.src} />
                    <Image alt={`pic59jpg`} src={pic59jpg.src} />
                    <Image alt={`pic60jpg`} src={pic60jpg.src} />
                    <Image alt={`pic61jpg`} src={pic61jpg.src} />
                    <Image alt={`pic62jpg`} src={pic62jpg.src} />
                    <Image alt={`pic63jpg`} src={pic63jpg.src} />
                    <Image alt={`pic64jpg`} src={pic64jpg.src} />
                    <Image alt={`pic65jpg`} src={pic65jpg.src} />
                    <Image alt={`pic66jpg`} src={pic66jpg.src} />
                    <Image alt={`pic67jpg`} src={pic67jpg.src} />
                    <Image alt={`pic68jpg`} src={pic68jpg.src} />
                    <Image alt={`pic69jpg`} src={pic69jpg.src} />
                    <Image alt={`pic70jpg`} src={pic70jpg.src} />
                    <Image alt={`pic71jpg`} src={pic71jpg.src} />
                    <Image alt={`pic72jpg`} src={pic72jpg.src} />
                    <Image alt={`pic73jpg`} src={pic73jpg.src} />
                    <Image alt={`pic74jpg`} src={pic74jpg.src} />
                    <Image alt={`pic75jpg`} src={pic75jpg.src} />
                    <Image alt={`pic76jpg`} src={pic76jpg.src} />
                    <Image alt={`pic77jpg`} src={pic77jpg.src} />
                    <Image alt={`pic78jpg`} src={pic78jpg.src} />
                    <Image alt={`pic79jpg`} src={pic79jpg.src} />
                    <Image alt={`pic80jpg`} src={pic80jpg.src} />
                </div>
            </div>
        </>
    );
}
